version: "3"

services:
  app:
    build: .
    container_name: micro-videos-typescript-app
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000

  postgres:
    image: bitnami/postgresql
    ports: 
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=pass
      - POSTGRESQL_DATABASE=microvideos
